name: videofy

services:
  postgres-dev:
    image: postgres:17-alpine
    container_name: videofy-dev
    restart: unless-stopped

    environment:
      POSTGRES_DB: videofy
      POSTGRES_USER: videofy
      POSTGRES_PASSWORD: videofy

    ports:
      - "6030:5432"

    volumes:
      - ./data/postgres-dev:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U videofy -d videofy"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - videofy-network

  postgres-prod:
    image: postgres:17-alpine
    container_name: videofy-prod
    restart: unless-stopped

    environment:
      POSTGRES_DB: videofy
      POSTGRES_USER: videofy
      POSTGRES_PASSWORD: videofy

    ports:
      - "6031:5432"

    volumes:
      - ./data/postgres-prod:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U videofy -d videofy"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - videofy-network

networks:
  videofy-network:
    driver: bridge